name: tfbio_env
dependencies:
- conda-forge::python=3.6
- marta-sd::cudatoolkit=8.0
- marta-sd::cudnn=5.1
- marta-sd::tensorflow-gpu=1.2
- openbabel::openbabel=2.4.1
- conda-forge::numpy=1.12.1
- conda-forge::matplotlib>=2.0
- conda-forge::seaborn>=0.7
